### ISSUE TITLE
install raylib for python 

### ISSUE THREAD

**Issue by Kaftorone** [electronstudio/raylib-python-cffi#150]
```
make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED
```
install using pip

```
pip3 install raylib 
```
the error
```
ERROR: Command errored out with exit status 1:                        command: /root/myenv/bin/python3 /tmp/tmpdbii0ued prepare_metadata_for_build_wheel /tmp/tmp9lveqmr6
         cwd: /tmp/pip-install-wl14yd6h/raylib                           Complete output (36 lines):
    not windows, trying Unix build
    Traceback (most recent call last):                                     File "/tmp/tmpdbii0ued", line 280, in <module>
        main()
      File "/tmp/tmpdbii0ued", line 263, in main                             json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpdbii0ued", line 133, in prepare_metadata_for_build_wheel                                                                      return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 376, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 319, in run_setup
        exec(code, locals())
      File "<string>", line 20, in <module>                                File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)                               File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 145, in setup                    _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 326, in __init__
        _Distribution.__init__(self, dist_attrs)                           File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 279, in __init__                 self.finalize_options()
      File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 682, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-3j6l2g_k/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords            ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-3j6l2g_k/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules                     add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-3j6l2g_k/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-3j6l2g_k/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)                                             File "raylib/build.py", line 220, in <module>                          build_unix()
      File "raylib/build.py", line 107, in build_unix
        raise Exception("ERROR: raylib not found by pkg-config.  Please install pkg-config and Raylib.")                                      Exception: ERROR: raylib not found by pkg-config.  Please install pkg-config and Raylib.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/myenv/bin/python3 /tmp/tmpdbii0ued prepare_metadata_for_build_wheel /tmp/tmp9lveqmr6 Check the logs for full command output.
```

**Comment by electronstudio** [comment]
Read the docs https://github.com/electronstudio/raylib-python-cffi/blob/master/BUILDING.rst

**Comment by Kaftorone** [comment]
> Read the docs https://github.com/electronstudio/raylib-python-cffi/blob/master/BUILDING.rst

> that is work thanks
