### ISSUE TITLE
PyInstaller Build Producing Broken Executable

### ISSUE THREAD

**Issue by Pebaz** [electronstudio/raylib-python-cffi#3]
Trying to test distribution of Raylib-Python-CFFI projects:

```python
# hello-world.py
from raylib.static import *

InitWindow(800, 450, b"Hello Raylib")
SetTargetFPS(60)

camera = ffi.new("struct Camera3D *", [
    [18.0, 16.0, 18.0],
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    45.0,
    0
])
SetCameraMode(camera[0], CAMERA_ORBITAL)

while not WindowShouldClose():
    UpdateCamera(camera)
    BeginDrawing()
    ClearBackground(RAYWHITE)
    BeginMode3D(camera[0])
    DrawGrid(20, 1.0)
    EndMode3D()
    DrawText(b"Hellow World", 190, 200, 20, VIOLET)
    EndDrawing()
CloseWindow()
```

### Now to build it

```bash
pyinstaller --onefile hello-world.py

# Test it
dist/hello-world.py
```

### Error message

```
Traceback (most recent call last):
  File "hello-world.py", line 1, in <module>
    from raylib.static import *
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\raylib\static\__init__.py", line 1, in <module>
ModuleNotFoundError: No module named '_cffi_backend'
[7316] Failed to execute script hello-world
```

**Comment by Pebaz** [comment]
Found solution:

```bash
pyinstaller --onefile --hidden-import=cffi hello-world.py
```

### Explaination

PyInstaller did not know that it needed to bundle CFFI, so adding the `--hidden-import=cffi` successfully added CFFI to the EXE bundle.

**Comment by electronstudio** [comment]
I will add an explicit _import cffi_ if it fixes this

**Comment by Pebaz** [comment]
I just tested this theory by adding `import cffi` to my test module's code and this worked perfectly!
I am assuming that if you add that to the base code that it will accomplish the same effect.
Good thinking!
