### ISSUE TITLE
Module 'version.py' not found while installing via pip

### ISSUE THREAD

**Issue by pkulev** [electronstudio/raylib-python-cffi#49]
Hi, trying to install via pip (python3.9):

```
╰─$ pip install raylib
Collecting raylib
  Using cached raylib-3.7.0.post9.tar.gz (71 kB)
    ERROR: Command errored out with exit status 1:
     command: /private/tmp/hui/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zf/d8kdk1ln39qf42k6676nb3980000gn/T/pip-install-kx_nuh68/raylib_01e3808c2aff44c09a7600fca69c9898/setup.py'"'"'; __file__='"'"'/private/var/folders/zf/d8kdk1ln39qf42k6676nb3980000gn/T/pip-install-kx_nuh68/raylib_01e3808c2aff44c09a7600fca69c9898/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zf/d8kdk1ln39qf42k6676nb3980000gn/T/pip-pip-egg-info-f01r36ra
         cwd: /private/var/folders/zf/d8kdk1ln39qf42k6676nb3980000gn/T/pip-install-kx_nuh68/raylib_01e3808c2aff44c09a7600fca69c9898/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zf/d8kdk1ln39qf42k6676nb3980000gn/T/pip-install-kx_nuh68/raylib_01e3808c2aff44c09a7600fca69c9898/setup.py", line 4, in <module>
        from version import __version__
    ModuleNotFoundError: No module named 'version'
```

I bet it's because version.py is not included in Manifest.in, I see it included already in https://github.com/electronstudio/raylib-python-cffi/commit/775d2da32df895e4c407d86b7d4a5e826bbd9424.

Please, publish fixed version into PyPI.

**Comment by electronstudio** [comment]
And what are the errors when you try to install 4.0a4 ?

**Comment by pkulev** [comment]
> btw what platform are you on that we don't have binary wheels for?

MacOS on m1



> And what are the errors when you try to install 4.0a4 ?

```
      File "raylib/build.py", line 152, in <module>
        build_mac()
      File "raylib/build.py", line 104, in build_mac
        ffibuilder.cdef(mangle("/usr/local/include/raylib.h"))
      File "raylib/build.py", line 31, in mangle
        for line in open(file):
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/include/raylib.h'
    BUILDING FOR MAC
    --------------------
```
