### ISSUE TITLE
Raylib not working : cannot import 'rl'

### ISSUE THREAD

**Issue by BluLogic** [electronstudio/raylib-python-cffi#59]
I'm on MacOS 12.1 and I installed Raylib using pip. I import it via `from pyray import *` but it resulted in the error
```Traceback (most recent call last):
  File "raylib.py", line 1, in <module>
    from pyray import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyray/__init__.py", line 15, in <module>
    from raylib import rl, ffi
ImportError: cannot import name 'rl' from 'raylib' (/Users/samate/PycharmProjects/MyPrograms/raylib.py)
```
I built raylib from source using pip but it resulted in the same error. Previous versions didn't work too. I tried `from raylib import *`
and this gave a different error
```Traceback (most recent call last):
  File "raylib.py", line 26, in <module>
    main()
  File "raylib.py", line 6, in main
    InitWindow(800, 450, b'hello world')
NameError: name 'InitWindow' is not defined
```
Finally trying `from raylib import rl` results in:
```Traceback (most recent call last):
  File "raylib.py", line 1, in <module>
    from raylib import rl
  File "raylib.py", line 1, in <module>
    from raylib import rl
ImportError: cannot import name 'rl' from partially initialized module 'raylib' (most likely due to a circular import) (raylib.py)
```

**Comment by electronstudio** [comment]
In Python, can't name your own program the same name as a library you are importing.

**Comment by BluLogic** [comment]
oh sorry what a dumb mistake :P

**Comment by electronstudio** [comment]
Don’t worry, we all make them.
